# Generated by Django 2.2.28 on 2023-01-23 20:46

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country", django_countries.fields.CountryField(max_length=2)),
                ("zip_code", models.CharField(max_length=32)),
                (
                    "forecast",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        editable=False, null=True
                    ),
                ),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
