# Generated by Django 5.2.16 on 2026-09-17 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weather", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="forecast",
            field=models.JSONField(editable=False, null=True),
        ),
    ]
